
SP_HELP  MST_COMPANY
SP_HELP  MST_DEDUCTEE

SELECT * FROM TRN_BASIC_INFO WHERE COMPANY_ID = 46

SELECT * FROM MST_ASSESSMENT 

SELECT * FROM TRN_CHALLAN WHERE BASIC_INFO_ID = 27

SELECT * FROM TRN_DEDUCTEE_DETAILS WHERE BASIC_INFO_ID = 27

--##########################################################
--##########################################################
SELECT  MST_COMPANY.COMPANY_ID          AS COMPANY_ID,        
		MST_COMPANY.COMPANY_NAME        AS COMPANY_NAME,        
		MST_COMPANY.TAN_NO              AS TAN_NO,        
		MST_COMPANY.PAN_NO              AS PAN_NO,        
		MST_COMPANY.ADDRESS1            AS ADDRESS1,        
		MST_COMPANY.ADDRESS2            AS ADDRESS2,        
		MST_COMPANY.ADDRESS3            AS ADDRESS3,        
		MST_COMPANY.ADDRESS4            AS ADDRESS4,        
		MST_COMPANY.ADDRESS5            AS ADDRESS5,        
		MST_COMPANY.STATE_ID            AS STATE_ID,        
		MST_STATE.STATE_NAME            AS STATE_NAME,        
		MST_COMPANY.PIN_CODE            AS PIN_CODE,        
		MST_COMPANY.PHONE               AS PHONE,        
		MST_COMPANY.STD                 AS STD,        
		MST_COMPANY.EMAIL               AS EMAIL,        
		MST_COMPANY.CIT_TDS_ADDRESS     AS CIT_TDS_ADDRESS,        
		MST_COMPANY.CIT_TDS_CITY        AS CIT_TDS_CITY,        
		MST_COMPANY.CIT_TDS_PINCODE     AS CIT_TDS_PINCODE,        
		MST_COMPANY.PERSON_NAME         AS PERSON_NAME,        
		MST_COMPANY.FATHER_NAME         AS FATHER_NAME,        
		MST_COMPANY.DESIGNATION         AS DESIGNATION,        
		MST_ASSESSMENT.ASST_YEAR        AS ASST_YEAR,        
		MST_ASSESSMENT.START_DATE       AS START_DATE,        
		MST_ASSESSMENT.END_DATE         AS END_DATE,        
		MST_DEDUCTEE.DEDUCTEE_ID        AS DEDUCTEE_ID,        
		MST_DEDUCTEE.DEDUCTEE_CODE      AS DEDUCTEE_CODE,        
		MST_DEDUCTEE.DEDUCTEE_NAME      AS DEDUCTEE_NAME,        
		MST_DEDUCTEE.DEDUCTEE_PAN       AS DEDUCTEE_PAN,        
		MST_DEDUCTEE.ADDRESS1           AS D_ADDRESS1,        
		MST_DEDUCTEE.ADDRESS2           AS D_ADDRESS2,        
		MST_DEDUCTEE.ADDRESS3           AS D_ADDRESS3,        
		MST_DEDUCTEE.ADDRESS4           AS D_ADDRESS4,        
		MST_DEDUCTEE.ADDRESS5           AS D_ADDRESS5,        
		MST_DEDUCTEE.STATE_ID           AS D_STATE_ID,        
		MST_STATE_D.STATE_NAME          AS D_STATE_NAME,        
		MST_DEDUCTEE.PIN_CODE           AS D_PIN_CODE,        
		MST_DEDUCTEE.MOBILE_NO          AS D_MOBILE_NO,        
		MST_DEDUCTEE.EMAIL              AS D_EMAIL,        
		TRN_CHALLAN.CHALLAN_ID          AS CHALLAN_ID,        
		TRN_CHALLAN.SECTION_ID          AS SECTION_ID,        
		TRN_CHALLAN.DEPOSIT_DATE        AS DEPOSIT_DATE,        
		TRN_CHALLAN.BSR_CODE            AS BSR_CODE,        
		TRN_CHALLAN.CHALLAN_NO          AS CHALLAN_NO,        
		TRN_CHALLAN.TRANSFER_VOUCHER_NO AS TRANSFER_VOUCHER_NO,        
		--TRN_CHALLAN.TOT_TAX             AS TOT_TAX,        
		--TRN_CHALLAN.CTRL_TOT_TAX        AS CTRL_TOT_TAX,        
		TRN_DEDUCTEE_DETAILS.PARTY_ID   AS PARTY_ID,        
		SUM(TRN_DEDUCTEE_DETAILS.TAX_DEPOSITED_AMOUNT) AS DEDUCTEE_TOTAL,        
		TRN_CHALLAN.BOOK_ENTRY          AS BOOK_ENTRY 
FROM   (((((((MST_COMPANY INNER JOIN MST_STATE               
		ON MST_COMPANY.STATE_ID          = MST_STATE.STATE_ID)         
		INNER JOIN TRN_BASIC_INFO              
		ON MST_COMPANY.COMPANY_ID        = TRN_BASIC_INFO.COMPANY_ID)         
		INNER JOIN MST_ASSESSMENT              
		ON TRN_BASIC_INFO.ASST_ID        = MST_ASSESSMENT.ASST_ID)         
		INNER JOIN TRN_CHALLAN              
		ON TRN_BASIC_INFO.BASIC_INFO_ID  = TRN_CHALLAN.BASIC_INFO_ID)         
		INNER JOIN TRN_DEDUCTEE_DETAILS              
		ON TRN_CHALLAN.CHALLAN_ID        = TRN_DEDUCTEE_DETAILS.CHALLAN_ID)         
		INNER JOIN MST_DEDUCTEE              
		ON TRN_DEDUCTEE_DETAILS.PARTY_ID = MST_DEDUCTEE.DEDUCTEE_ID)         
		LEFT JOIN  MST_STATE AS MST_STATE_D             
		ON MST_DEDUCTEE.STATE_ID         = MST_STATE_D.STATE_ID) 
WHERE  TRN_BASIC_INFO.BASIC_INFO_ID          = 31 
AND    TRN_DEDUCTEE_DETAILS.PARTY_ID IN     (3845) 
GROUP BY MST_COMPANY.COMPANY_ID,       
		MST_COMPANY.COMPANY_NAME,       
		MST_COMPANY.TAN_NO,       
		MST_COMPANY.PAN_NO,       
		MST_COMPANY.ADDRESS1,       
		MST_COMPANY.ADDRESS2,       
		MST_COMPANY.ADDRESS3,       
		MST_COMPANY.ADDRESS4,       
		MST_COMPANY.ADDRESS5,       
		MST_COMPANY.STATE_ID,       
		MST_STATE.STATE_NAME,       
		MST_COMPANY.PIN_CODE,       
		MST_COMPANY.PHONE,       
		MST_COMPANY.STD,       
		MST_COMPANY.EMAIL,       
		MST_COMPANY.CIT_TDS_ADDRESS,       
		MST_COMPANY.CIT_TDS_CITY,       
		MST_COMPANY.CIT_TDS_PINCODE,       
		MST_COMPANY.PERSON_NAME,       
		MST_COMPANY.FATHER_NAME,       
		MST_COMPANY.DESIGNATION,       
		MST_ASSESSMENT.ASST_YEAR,       
		MST_ASSESSMENT.START_DATE,       
		MST_ASSESSMENT.END_DATE,       
		MST_DEDUCTEE.DEDUCTEE_ID,       
		MST_DEDUCTEE.DEDUCTEE_CODE,       
		MST_DEDUCTEE.DEDUCTEE_NAME,       
		MST_DEDUCTEE.DEDUCTEE_PAN,       
		MST_DEDUCTEE.ADDRESS1,       
		MST_DEDUCTEE.ADDRESS2,       
		MST_DEDUCTEE.ADDRESS3,       
		MST_DEDUCTEE.ADDRESS4,       
		MST_DEDUCTEE.ADDRESS5,       
		MST_DEDUCTEE.STATE_ID,       
		MST_STATE_D.STATE_NAME,       
		MST_DEDUCTEE.PIN_CODE,       
		MST_DEDUCTEE.MOBILE_NO,       
		MST_DEDUCTEE.EMAIL,       
		TRN_CHALLAN.CHALLAN_ID,       
		TRN_CHALLAN.SECTION_ID,       
		TRN_CHALLAN.DEPOSIT_DATE,       
		TRN_CHALLAN.BSR_CODE,       
		TRN_CHALLAN.CHALLAN_NO,       
		TRN_CHALLAN.TRANSFER_VOUCHER_NO,   
		TRN_DEDUCTEE_DETAILS.PARTY_ID,       
--		TRN_DEDUCTEE_DETAILS.TAX_DEPOSITED_AMOUNT,       
		TRN_CHALLAN.BOOK_ENTRY 
ORDER BY MST_DEDUCTEE.DEDUCTEE_ID,       TRN_CHALLAN.DEPOSIT_DATE,       TRN_CHALLAN.CHALLAN_ID
--##########################################################
--##########################################################
SELECT TRN_CHALLAN.CHALLAN_ID,
       TRN_DEDUCTEE_DETAILS.PARTY_ID,
       TRN_DEDUCTEE_DETAILS.PAYMENT_AMOUNT,
       TRN_CHALLAN.SECTION_ID,
       MST_SECTION.SECTION_DESCRIPTION,
       TRN_DEDUCTEE_DETAILS.PAYMENT_DATE
FROM   TRN_BASIC_INFO,
       TRN_CHALLAN,
       TRN_DEDUCTEE_DETAILS,
       MST_SECTION
WHERE  TRN_CHALLAN.BASIC_INFO_ID     = TRN_BASIC_INFO.BASIC_INFO_ID
AND    TRN_CHALLAN.CHALLAN_ID        = TRN_DEDUCTEE_DETAILS.CHALLAN_ID
AND    TRN_CHALLAN.SECTION_ID        = MST_SECTION.SECTION_ID
AND    TRN_BASIC_INFO.BASIC_INFO_ID  = 31
AND    TRN_DEDUCTEE_DETAILS.PARTY_ID IN (3845)
--##########################################################
--##########################################################
SELECT TRN_DEDUCTEE_DETAILS.PARTY_ID,
       TRN_CHALLAN.SECTION_ID,
       TRN_BASIC_INFO.QTR,
       TRN_BASIC_INFO.RECEIPT_NO,
       SUM(TRN_DEDUCTEE_DETAILS.TOTAL_AMOUNT) AS TOTAL_AMOUNT,
       SUM(TRN_DEDUCTEE_DETAILS.TAX_DEPOSITED_AMOUNT) AS TAX_DEPOSITED_AMOUNT
FROM   TRN_BASIC_INFO,
       TRN_CHALLAN,
       TRN_DEDUCTEE_DETAILS
WHERE  TRN_BASIC_INFO.BASIC_INFO_ID  = TRN_DEDUCTEE_DETAILS.BASIC_INFO_ID
AND    TRN_CHALLAN.CHALLAN_ID        = TRN_DEDUCTEE_DETAILS.CHALLAN_ID
AND    TRN_BASIC_INFO.BASIC_INFO_ID  = 31
AND    TRN_DEDUCTEE_DETAILS.PARTY_ID IN (3845)
GROUP BY TRN_DEDUCTEE_DETAILS.PARTY_ID,
       TRN_CHALLAN.SECTION_ID,
       TRN_BASIC_INFO.RECEIPT_NO,
       TRN_BASIC_INFO.QTR,
       TRN_BASIC_INFO.RECEIPT_NO    
--@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
SELECT SUM(TRN_DEDUCTEE_DETAILS.TAX_DEPOSITED_AMOUNT) AS TAX_DEPOSITED_AMOUNT
FROM   TRN_DEDUCTEE_DETAILS
WHERE  BASIC_INFO_ID  = 27
AND    PARTY_ID IN (3842)
--##########################################################
--##########################################################

SELECT  MST_COMPANY.COMPANY_ID          AS COMPANY_ID,
        MST_COMPANY.COMPANY_NAME        AS COMPANY_NAME,            
        MST_COMPANY.TAN_NO              AS TAN_NO,            
        MST_COMPANY.PAN_NO              AS PAN_NO,            
        MST_COMPANY.ADDRESS1            AS ADDRESS1,            
        MST_COMPANY.ADDRESS2            AS ADDRESS2,            
        MST_COMPANY.ADDRESS3            AS ADDRESS3,            
        MST_COMPANY.ADDRESS4            AS ADDRESS4,            
        MST_COMPANY.ADDRESS5            AS ADDRESS5,            
        MST_COMPANY.STATE_ID            AS STATE_ID,            
        MST_STATE.STATE_NAME            AS STATE_NAME,            
        MST_COMPANY.PIN_CODE            AS PIN_CODE,            
        MST_COMPANY.PHONE               AS PHONE,            
        MST_COMPANY.STD                 AS STD,            
        MST_COMPANY.EMAIL               AS EMAIL,            
        MST_COMPANY.CIT_TDS_ADDRESS     AS CIT_TDS_ADDRESS,            
        MST_COMPANY.CIT_TDS_CITY        AS CIT_TDS_CITY,            
        MST_COMPANY.CIT_TDS_PINCODE     AS CIT_TDS_PINCODE,            
        MST_ASSESSMENT.ASST_YEAR        AS ASST_YEAR,                  
        MST_ASSESSMENT.START_DATE       AS START_DATE,                  
        MST_ASSESSMENT.END_DATE         AS END_DATE,            
        MST_DEDUCTEE.DEDUCTEE_ID        AS DEDUCTEE_ID,            
        MST_DEDUCTEE.DEDUCTEE_CODE      AS DEDUCTEE_CODE,            
        MST_DEDUCTEE.DEDUCTEE_NAME      AS DEDUCTEE_NAME,            
        MST_DEDUCTEE.DEDUCTEE_PAN       AS DEDUCTEE_PAN,            
        MST_DEDUCTEE.ADDRESS1           AS D_ADDRESS1,            
        MST_DEDUCTEE.ADDRESS2           AS D_ADDRESS2,            
        MST_DEDUCTEE.ADDRESS3           AS D_ADDRESS3,            
        MST_DEDUCTEE.ADDRESS4           AS D_ADDRESS4,            
        MST_DEDUCTEE.ADDRESS5           AS D_ADDRESS5,            
        MST_DEDUCTEE.STATE_ID           AS D_STATE_ID,            
        MST_STATE_D.STATE_NAME          AS D_STATE_NAME,            
        MST_DEDUCTEE.PIN_CODE           AS D_PIN_CODE,            
        MST_DEDUCTEE.MOBILE_NO          AS D_MOBILE_NO,            
        MST_DEDUCTEE.EMAIL              AS D_EMAIL,            
        TRN_CHALLAN.CHALLAN_ID          AS CHALLAN_ID,            
        TRN_CHALLAN.SECTION_ID          AS SECTION_ID,            
        TRN_CHALLAN.DEPOSIT_DATE        AS DEPOSIT_DATE,            
        TRN_CHALLAN.BSR_CODE            AS BSR_CODE,            
        TRN_CHALLAN.CHALLAN_NO          AS CHALLAN_NO,            
        TRN_CHALLAN.TRANSFER_VOUCHER_NO AS TRANSFER_VOUCHER_NO,            
        TRN_CHALLAN.TOT_TAX             AS TOT_TAX,            
        TRN_DEDUCTEE_DETAILS.PARTY_ID   AS PARTY_ID      
FROM   (((((((MST_COMPANY INNER JOIN MST_STATE              
				ON MST_COMPANY.STATE_ID          = MST_STATE.STATE_ID)      
		INNER JOIN TRN_BASIC_INFO              
				ON MST_COMPANY.COMPANY_ID        = TRN_BASIC_INFO.COMPANY_ID)
		INNER JOIN MST_ASSESSMENT              
				ON TRN_BASIC_INFO.ASST_ID        = MST_ASSESSMENT.ASST_ID)      
		INNER JOIN TRN_CHALLAN
				ON TRN_BASIC_INFO.BASIC_INFO_ID  = TRN_CHALLAN.BASIC_INFO_ID)
		INNER JOIN TRN_DEDUCTEE_DETAILS              
				ON TRN_CHALLAN.CHALLAN_ID        = TRN_DEDUCTEE_DETAILS.CHALLAN_ID)   
		INNER JOIN MST_DEDUCTEE              
				ON TRN_DEDUCTEE_DETAILS.PARTY_ID = MST_DEDUCTEE.DEDUCTEE_ID)
		LEFT JOIN  MST_STATE AS MST_STATE_D              
				ON MST_DEDUCTEE.STATE_ID         = MST_STATE_D.STATE_ID)
WHERE  TRN_BASIC_INFO.BASIC_INFO_ID  = 28      
AND    TRN_DEDUCTEE_DETAILS.PARTY_ID IN (3848)      
ORDER BY MST_DEDUCTEE.DEDUCTEE_NAME,TRN_CHALLAN.CHALLAN_ID
---------------------------------------------------------
---------------------------------------------------------
SELECT  MST_COMPANY.COMPANY_ID          AS COMPANY_ID,        
		MST_COMPANY.COMPANY_NAME        AS COMPANY_NAME,        
		MST_COMPANY.TAN_NO              AS TAN_NO,        
		MST_COMPANY.PAN_NO              AS PAN_NO,        
		MST_COMPANY.ADDRESS1            AS ADDRESS1,        
		MST_COMPANY.ADDRESS2            AS ADDRESS2,        
		MST_COMPANY.ADDRESS3            AS ADDRESS3,        
		MST_COMPANY.ADDRESS4            AS ADDRESS4,        
		MST_COMPANY.ADDRESS5            AS ADDRESS5,        
		MST_COMPANY.STATE_ID            AS STATE_ID,        
		MST_STATE.STATE_NAME            AS STATE_NAME,        
		MST_COMPANY.PIN_CODE            AS PIN_CODE,        
		MST_COMPANY.PHONE               AS PHONE,        
		MST_COMPANY.STD                 AS STD,        
		MST_COMPANY.EMAIL               AS EMAIL,        
		MST_COMPANY.CIT_TDS_ADDRESS     AS CIT_TDS_ADDRESS,        
		MST_COMPANY.CIT_TDS_CITY        AS CIT_TDS_CITY,        
		MST_COMPANY.CIT_TDS_PINCODE     AS CIT_TDS_PINCODE,        
		MST_ASSESSMENT.ASST_YEAR        AS ASST_YEAR,        
		MST_ASSESSMENT.START_DATE       AS START_DATE,       
		MST_ASSESSMENT.END_DATE         AS END_DATE,        
		MST_DEDUCTEE.DEDUCTEE_ID        AS DEDUCTEE_ID,      
		MST_DEDUCTEE.DEDUCTEE_CODE      AS DEDUCTEE_CODE,  
		MST_DEDUCTEE.DEDUCTEE_NAME      AS DEDUCTEE_NAME, 
		MST_DEDUCTEE.DEDUCTEE_PAN       AS DEDUCTEE_PAN,  
		MST_DEDUCTEE.ADDRESS1           AS D_ADDRESS1,       
		MST_DEDUCTEE.ADDRESS2           AS D_ADDRESS2,        
		MST_DEDUCTEE.ADDRESS3           AS D_ADDRESS3,        
		MST_DEDUCTEE.ADDRESS4           AS D_ADDRESS4,        
		MST_DEDUCTEE.ADDRESS5           AS D_ADDRESS5,        
		MST_DEDUCTEE.STATE_ID           AS D_STATE_ID,        
		MST_STATE_D.STATE_NAME          AS D_STATE_NAME,      
		MST_DEDUCTEE.PIN_CODE           AS D_PIN_CODE,  
		MST_DEDUCTEE.MOBILE_NO          AS D_MOBILE_NO,  
		MST_DEDUCTEE.EMAIL              AS D_EMAIL,      
		TRN_CHALLAN.CHALLAN_ID          AS CHALLAN_ID,       
		TRN_CHALLAN.SECTION_ID          AS SECTION_ID,       
		TRN_CHALLAN.DEPOSIT_DATE        AS DEPOSIT_DATE,   
		TRN_CHALLAN.BSR_CODE            AS BSR_CODE,   
		TRN_CHALLAN.CHALLAN_NO          AS CHALLAN_NO, 
		TRN_CHALLAN.TRANSFER_VOUCHER_NO AS TRANSFER_VOUCHER_NO, 
		TRN_CHALLAN.TOT_TAX             AS TOT_TAX,        
		TRN_CHALLAN.CTRL_TOT_TAX        AS DEDUCTEE_TOTAL,        
		TRN_DEDUCTEE_DETAILS.PARTY_ID   AS PARTY_ID 
FROM   (((((((MST_COMPANY INNER JOIN MST_STATE               
		ON MST_COMPANY.STATE_ID          = MST_STATE.STATE_ID)         
		INNER JOIN TRN_BASIC_INFO              
		ON MST_COMPANY.COMPANY_ID        = TRN_BASIC_INFO.COMPANY_ID)         
		INNER JOIN MST_ASSESSMENT              
		ON TRN_BASIC_INFO.ASST_ID        = MST_ASSESSMENT.ASST_ID)         
		INNER JOIN TRN_CHALLAN              
		ON TRN_BASIC_INFO.BASIC_INFO_ID  = TRN_CHALLAN.BASIC_INFO_ID)         
		INNER JOIN TRN_DEDUCTEE_DETAILS              
		ON TRN_CHALLAN.CHALLAN_ID        = TRN_DEDUCTEE_DETAILS.CHALLAN_ID)         
		INNER JOIN MST_DEDUCTEE              
		ON TRN_DEDUCTEE_DETAILS.PARTY_ID = MST_DEDUCTEE.DEDUCTEE_ID)         
		LEFT JOIN  MST_STATE AS MST_STATE_D             
		ON MST_DEDUCTEE.STATE_ID         = MST_STATE_D.STATE_ID) 
WHERE  TRN_CHALLAN.BOOK_ENTRY        = 0
AND    TRN_BASIC_INFO.BASIC_INFO_ID  = 27
AND    TRN_DEDUCTEE_DETAILS.PARTY_ID IN (3848) 
GROUP BY MST_COMPANY.COMPANY_ID,        
		MST_COMPANY.COMPANY_NAME,        
		MST_COMPANY.TAN_NO,        
		MST_COMPANY.PAN_NO,        
		MST_COMPANY.ADDRESS1,        
		MST_COMPANY.ADDRESS2,        
		MST_COMPANY.ADDRESS3,        
		MST_COMPANY.ADDRESS4,        
		MST_COMPANY.ADDRESS5,        
		MST_COMPANY.STATE_ID,        
		MST_STATE.STATE_NAME,        
		MST_COMPANY.PIN_CODE,        
		MST_COMPANY.PHONE,        
		MST_COMPANY.STD,        
		MST_COMPANY.EMAIL,        
		MST_COMPANY.CIT_TDS_ADDRESS,        
		MST_COMPANY.CIT_TDS_CITY,        
		MST_COMPANY.CIT_TDS_PINCODE,        
		MST_ASSESSMENT.ASST_YEAR,        
		MST_ASSESSMENT.START_DATE,       
		MST_ASSESSMENT.END_DATE,        
		MST_DEDUCTEE.DEDUCTEE_ID,      
		MST_DEDUCTEE.DEDUCTEE_CODE,  
		MST_DEDUCTEE.DEDUCTEE_NAME, 
		MST_DEDUCTEE.DEDUCTEE_PAN,  
		MST_DEDUCTEE.ADDRESS1,       
		MST_DEDUCTEE.ADDRESS2,        
		MST_DEDUCTEE.ADDRESS3,        
		MST_DEDUCTEE.ADDRESS4,        
		MST_DEDUCTEE.ADDRESS5,        
		MST_DEDUCTEE.STATE_ID,        
		MST_STATE_D.STATE_NAME,      
		MST_DEDUCTEE.PIN_CODE,  
		MST_DEDUCTEE.MOBILE_NO,  
		MST_DEDUCTEE.EMAIL,      
		TRN_CHALLAN.CHALLAN_ID,       
		TRN_CHALLAN.SECTION_ID,       
		TRN_CHALLAN.DEPOSIT_DATE,   
		TRN_CHALLAN.BSR_CODE,   
		TRN_CHALLAN.CHALLAN_NO, 
		TRN_CHALLAN.TRANSFER_VOUCHER_NO, 
		TRN_CHALLAN.TOT_TAX,        
		TRN_CHALLAN.CTRL_TOT_TAX,        
		TRN_DEDUCTEE_DETAILS.PARTY_ID 
ORDER BY MST_DEDUCTEE.DEDUCTEE_NAME,        TRN_CHALLAN.CHALLAN_ID
---------------------------------------------------
---------------------------------------------------
-- BOOK ENTRY
--SELECT * FROM TRN_CHALLAN ORDER BY BASIC_INFO_ID
------------------
--UPDATE TRN_CHALLAN
--SET    BOOK_ENTRY = 0
------------------
--UPDATE TRN_CHALLAN
--SET    BOOK_ENTRY = 1
--WHERE  TRANSFER_VOUCHER_NO <> ''
------------------
--UPDATE TRN_CHALLAN
--SET    BOOK_ENTRY = 1
--WHERE  TOT_TAX > 0
--AND    TRANSFER_VOUCHER_NO = ''
--AND    BSR_CODE            = ''
--AND    CHALLAN_NO          = ''
---
SELECT  MST_COMPANY.COMPANY_ID          AS COMPANY_ID,
		MST_DEDUCTEE.DEDUCTEE_ID        AS DEDUCTEE_ID,  
		TRN_CHALLAN.CHALLAN_ID          AS CHALLAN_ID,       
		TRN_CHALLAN.SECTION_ID          AS SECTION_ID,       
		TRN_CHALLAN.DEPOSIT_DATE        AS DEPOSIT_DATE,   
		TRN_CHALLAN.BSR_CODE            AS BSR_CODE,   
		TRN_CHALLAN.CHALLAN_NO          AS CHALLAN_NO, 
		TRN_CHALLAN.TRANSFER_VOUCHER_NO AS TRANSFER_VOUCHER_NO, 
		TRN_CHALLAN.TOT_TAX             AS TOT_TAX,        
		TRN_CHALLAN.CTRL_TOT_TAX        AS DEDUCTEE_TOTAL,        
		TRN_DEDUCTEE_DETAILS.PARTY_ID   AS PARTY_ID,
        TRN_CHALLAN.BOOK_ENTRY          AS BOOK_ENTRY 
FROM   ((((MST_COMPANY INNER JOIN TRN_BASIC_INFO              
		ON MST_COMPANY.COMPANY_ID        = TRN_BASIC_INFO.COMPANY_ID)         
		INNER JOIN TRN_CHALLAN              
		ON TRN_BASIC_INFO.BASIC_INFO_ID  = TRN_CHALLAN.BASIC_INFO_ID)         
		INNER JOIN TRN_DEDUCTEE_DETAILS              
		ON TRN_CHALLAN.CHALLAN_ID        = TRN_DEDUCTEE_DETAILS.CHALLAN_ID)         
		INNER JOIN MST_DEDUCTEE              
		ON TRN_DEDUCTEE_DETAILS.PARTY_ID = MST_DEDUCTEE.DEDUCTEE_ID)         
WHERE  TRN_CHALLAN.BOOK_ENTRY        = 1
AND    TRN_BASIC_INFO.BASIC_INFO_ID  = 27
--AND    TRN_DEDUCTEE_DETAILS.PARTY_ID IN (3845) 
GROUP BY MST_COMPANY.COMPANY_ID,    
		MST_DEDUCTEE.DEDUCTEE_ID,  
		TRN_CHALLAN.CHALLAN_ID,       
		TRN_CHALLAN.SECTION_ID,       
		TRN_CHALLAN.DEPOSIT_DATE,   
		TRN_CHALLAN.BSR_CODE,   
		TRN_CHALLAN.CHALLAN_NO, 
		TRN_CHALLAN.TRANSFER_VOUCHER_NO, 
		TRN_CHALLAN.TOT_TAX,        
		TRN_CHALLAN.CTRL_TOT_TAX,        
		TRN_DEDUCTEE_DETAILS.PARTY_ID,
        TRN_CHALLAN.BOOK_ENTRY 
ORDER BY TRN_CHALLAN.DEPOSIT_DATE
-------------------------------
SELECT  MST_COMPANY.COMPANY_ID          AS COMPANY_ID,                                MST_DEDUCTEE.DEDUCTEE_ID        AS DEDUCTEE_ID,                                TRN_CHALLAN.CHALLAN_ID          AS CHALLAN_ID,                                TRN_CHALLAN.SECTION_ID          AS SECTION_ID,                                TRN_CHALLAN.DEPOSIT_DATE        AS DEPOSIT_DATE,                                TRN_CHALLAN.BSR_CODE            AS BSR_CODE,                                TRN_CHALLAN.CHALLAN_NO          AS CHALLAN_NO,                                TRN_CHALLAN.TRANSFER_VOUCHER_NO AS TRANSFER_VOUCHER_NO,                                TRN_CHALLAN.TOT_TAX             AS TOT_TAX,                                TRN_CHALLAN.CTRL_TOT_TAX        AS DEDUCTEE_TOTAL,                                TRN_DEDUCTEE_DETAILS.PARTY_ID   AS PARTY_ID,                                TRN_CHALLAN.BOOK_ENTRY          AS BOOK_ENTRY                          FROM   ((((MST_COMPANY INNER JOIN TRN_BASIC_INFO                                     ON MST_COMPANY.COMPANY_ID        = TRN_BASIC_INFO.COMPANY_ID)                                 INNER JOIN TRN_CHALLAN                                      ON TRN_BASIC_INFO.BASIC_INFO_ID  = TRN_CHALLAN.BASIC_INFO_ID)                                 INNER JOIN TRN_DEDUCTEE_DETAILS                                     ON TRN_CHALLAN.CHALLAN_ID        = TRN_DEDUCTEE_DETAILS.CHALLAN_ID)                                 INNER JOIN MST_DEDUCTEE                                      ON TRN_DEDUCTEE_DETAILS.PARTY_ID = MST_DEDUCTEE.DEDUCTEE_ID)                           WHERE  TRN_CHALLAN.BOOK_ENTRY        = 1                           AND    TRN_BASIC_INFO.BASIC_INFO_ID  = 27                           AND    TRN_DEDUCTEE_DETAILS.PARTY_ID IN (3845)                           GROUP BY MST_COMPANY.COMPANY_ID,                                 MST_DEDUCTEE.DEDUCTEE_ID,                                 TRN_CHALLAN.CHALLAN_ID,                                 TRN_CHALLAN.SECTION_ID,                                 TRN_CHALLAN.DEPOSIT_DATE,                                 TRN_CHALLAN.BSR_CODE,                                 TRN_CHALLAN.CHALLAN_NO,                                 TRN_CHALLAN.TRANSFER_VOUCHER_NO,                                 TRN_CHALLAN.TOT_TAX,                                 TRN_CHALLAN.CTRL_TOT_TAX,                                 TRN_DEDUCTEE_DETAILS.PARTY_ID,                                 TRN_CHALLAN.BOOK_ENTRY                           ORDER BY TRN_CHALLAN.DEPOSIT_DATE





