
SELECT * FROM MST_ASSESSMENT

SELECT DISTINCT MST_ASSESSMENT.ASST_ID,
       MST_ASSESSMENT.ASST_YEAR
FROM   MST_ASSESSMENT,
       TRN_BASIC_INFO
WHERE  MST_ASSESSMENT.ASST_ID = TRN_BASIC_INFO.ASST_ID


SELECT * FROM TRN_BASIC_INFO

SELECT START_DATE
FROM   MST_ASSESSMENT
WHERE  ASST_ID = (SELECT MAX(ASST_ID) FROM MST_ASSESSMENT)


SELECT DISTINCT MST_DEDUCTEE.DEDUCTEE_ID,
       MST_DEDUCTEE.DEDUCTEE_NAME,
       MST_DEDUCTEE.DEDUCTEE_PAN
FROM   TRN_BASIC_INFO,
       TRN_CHALLAN,
       TRN_DEDUCTEE_DETAILS,
       MST_DEDUCTEE
WHERE  TRN_BASIC_INFO.BASIC_INFO_ID = TRN_CHALLAN.BASIC_INFO_ID
AND    TRN_BASIC_INFO.BASIC_INFO_ID = TRN_DEDUCTEE_DETAILS.BASIC_INFO_ID 
AND    TRN_DEDUCTEE_DETAILS.PARTY_ID = MST_DEDUCTEE.DEDUCTEE_ID
AND    TRN_BASIC_INFO.FORM_NO IN ('26Q', '27Q', '27EQ')
--AND    TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE >=
--AND    TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE <=

SELECT MST_DEDUCTEE.DEDUCTEE_ID,
       MST_DEDUCTEE.DEDUCTEE_CODE,
       MST_DEDUCTEE.DEDUCTEE_NAME,
       MST_DEDUCTEE.DEDUCTEE_PAN,
       TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE,
       MST_SECTION.SECTION_NO,
       TRN_DEDUCTEE_DETAILS.PAYMENT_AMOUNT,
       TRN_DEDUCTEE_DETAILS.RATE,
       TRN_DEDUCTEE_DETAILS.TOTAL_AMOUNT,
       TRN_DEDUCTEE_DETAILS.TAX_DEPOSITED_AMOUNT,
       TRN_CHALLAN.CHALLAN_NO,
       TRN_CHALLAN.DEPOSIT_DATE
FROM   TRN_BASIC_INFO,
       TRN_CHALLAN,
       TRN_DEDUCTEE_DETAILS,
       MST_DEDUCTEE,
       MST_SECTION
WHERE  TRN_BASIC_INFO.BASIC_INFO_ID  = TRN_CHALLAN.BASIC_INFO_ID
AND    TRN_CHALLAN.CHALLAN_ID  = TRN_DEDUCTEE_DETAILS.CHALLAN_ID 
AND    TRN_DEDUCTEE_DETAILS.PARTY_ID = MST_DEDUCTEE.DEDUCTEE_ID
AND    TRN_CHALLAN.SECTION_ID        = MST_SECTION.SECTION_ID
AND    TRN_BASIC_INFO.FORM_NO        IN ('26Q', '27Q', '27EQ')
AND    TRN_DEDUCTEE_DETAILS.PARTY_ID IN(3845)
AND    TRN_BASIC_INFO.COMPANY_ID = 47
--AND    TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE >=
--AND    TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE <=

SELECT *
FROM TRN_CHALLAN

SELECT CASE WHEN CHALLAN_NO = '' THEN TRANSFER_VOUCHER_NO ELSE CHALLAN_NO END AS RT
FROM TRN_CHALLAN

SELECT MST_DEDUCTEE.DEDUCTEE_ID                  AS DEDUCTEE_ID,      
		IIF(MST_DEDUCTEE.DEDUCTEE_CODE='01', 'Company', 'Non-Company') AS DEDUCTEE_CODE,       
		MST_DEDUCTEE.DEDUCTEE_NAME                AS DEDUCTEE_NAME,       
		MST_DEDUCTEE.DEDUCTEE_PAN                 AS DEDUCTEE_PAN,       
		TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE        AS DEDUCTED_DATE,       
		MST_SECTION.SECTION_NO                    AS SECTION_NO,       
		TRN_DEDUCTEE_DETAILS.PAYMENT_AMOUNT       AS PAYMENT_AMOUNT,       
		TRN_DEDUCTEE_DETAILS.RATE                 AS RATE,       
		TRN_DEDUCTEE_DETAILS.TOTAL_AMOUNT         AS TOTAL_AMOUNT,       
		TRN_DEDUCTEE_DETAILS.TAX_DEPOSITED_AMOUNT AS TAX_DEPOSITED_AMOUNT,       
		IIF(TRN_CHALLAN.CHALLAN_NO = '', 'TRN_CHALLAN.TRANSFER_VOUCHER_NO', 'TRN_CHALLAN.CHALLAN_NO') AS CHLN,
       TRN_CHALLAN.CHALLAN_NO                    AS CHALLAN_NO,       TRN_CHALLAN.TRANSFER_VOUCHER_NO           AS TRANSFER_VOUCHER_NO,       TRN_CHALLAN.DEPOSIT_DATE                  AS DEPOSIT_DATE,       TRN_DEDUCTEE_DETAILS.NON_DEDUCTION_FLAG   AS NON_DEDUCTION_FLAG FROM   TRN_BASIC_INFO,       TRN_CHALLAN,       TRN_DEDUCTEE_DETAILS,       MST_DEDUCTEE,       MST_SECTION WHERE  TRN_BASIC_INFO.BASIC_INFO_ID       = TRN_CHALLAN.BASIC_INFO_ID AND    TRN_CHALLAN.CHALLAN_ID             = TRN_DEDUCTEE_DETAILS.CHALLAN_ID AND    TRN_DEDUCTEE_DETAILS.PARTY_ID      = MST_DEDUCTEE.DEDUCTEE_ID AND    TRN_CHALLAN.SECTION_ID             = MST_SECTION.SECTION_ID AND    TRN_BASIC_INFO.FORM_NO            IN('26Q') AND    TRN_DEDUCTEE_DETAILS.PARTY_ID     IN(3852,3853,3854,3851,3850) AND    TRN_BASIC_INFO.COMPANY_ID           = 47 AND    TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE >= #04/01/2010# AND    TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE <= #12/15/2010# 

SELECT MST_DEDUCTEE.DEDUCTEE_ID                  AS DEDUCTEE_ID,      IIF(MST_DEDUCTEE.DEDUCTEE_CODE='01', 'Company', 'Non-Company') AS DEDUCTEE_CODE,       MST_DEDUCTEE.DEDUCTEE_NAME                AS DEDUCTEE_NAME,       MST_DEDUCTEE.DEDUCTEE_PAN                 AS DEDUCTEE_PAN,       TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE        AS DEDUCTED_DATE,       MST_SECTION.SECTION_NO                    AS SECTION_NO,       TRN_DEDUCTEE_DETAILS.PAYMENT_AMOUNT       AS PAYMENT_AMOUNT,       TRN_DEDUCTEE_DETAILS.RATE                 AS RATE,       TRN_DEDUCTEE_DETAILS.TOTAL_AMOUNT         AS TOTAL_AMOUNT,       TRN_DEDUCTEE_DETAILS.TAX_DEPOSITED_AMOUNT AS TAX_DEPOSITED_AMOUNT,       IIF(TRN_CHALLAN.CHALLAN_NO = '', TRN_CHALLAN.TRANSFER_VOUCHER_NO, TRN_CHALLAN.CHALLAN_NO) AS CHLN,       TRN_CHALLAN.CHALLAN_NO                    AS CHALLAN_NO,       TRN_CHALLAN.TRANSFER_VOUCHER_NO           AS TRANSFER_VOUCHER_NO,       TRN_CHALLAN.DEPOSIT_DATE                  AS DEPOSIT_DATE,       TRN_DEDUCTEE_DETAILS.NON_DEDUCTION_FLAG   AS NON_DEDUCTION_FLAG FROM   TRN_BASIC_INFO,       TRN_CHALLAN,       TRN_DEDUCTEE_DETAILS,       MST_DEDUCTEE,       MST_SECTION WHERE  TRN_BASIC_INFO.BASIC_INFO_ID       = TRN_CHALLAN.BASIC_INFO_ID AND    TRN_CHALLAN.CHALLAN_ID             = TRN_DEDUCTEE_DETAILS.CHALLAN_ID AND    TRN_DEDUCTEE_DETAILS.PARTY_ID      = MST_DEDUCTEE.DEDUCTEE_ID AND    TRN_CHALLAN.SECTION_ID             = MST_SECTION.SECTION_ID AND    TRN_BASIC_INFO.FORM_NO            IN('26Q') AND    TRN_DEDUCTEE_DETAILS.PARTY_ID     IN(3842,3845,3843,3847,3846,3849,3848) AND    TRN_BASIC_INFO.COMPANY_ID           = 46 
AND    TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE >= #04/01/2010# 
AND    TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE <= #12/15/2010# 





SELECT * FROM MST_ASSESSMENT

--01/04/2010

SELECT ASST_ID 
FROM   MST_ASSESSMENT
WHERE  START_DATE >= '04/10/2010'
AND    START_DATE <= '04/10/2010'

SELECT ASST_ID 
FROM   MST_ASSESSMENT
WHERE  END_DATE >= '04/01/2010'
AND    END_DATE <= '04/01/2010'

SELECT ASST_ID 
FROM   MST_ASSESSMENT
WHERE  '04/01/2009' BETWEEN START_DATE AND END_DATE

SELECT ASST_ID 
FROM   MST_ASSESSMENT
WHERE  '12/15/2010' BETWEEN START_DATE AND END_DATE



SELECT * FROM TRN_BASIC_INFO
SELECT * FROM MST_SECTION
SELECT * FROM TRN_CHALLAN

SELECT DISTINCT MST_SECTION.SECTION_ID          AS SECTION_ID,
       MST_SECTION.SECTION_NO          AS SECTION_NO,
       MST_SECTION.SECTION_DESCRIPTION AS SECTION_DESCRIPTION
FROM   MST_SECTION,
       TRN_CHALLAN,
       TRN_BASIC_INFO
WHERE  MST_SECTION.SECTION_ID      = TRN_CHALLAN.SECTION_ID
AND    TRN_BASIC_INFO.BASIC_INFO_ID = TRN_CHALLAN.BASIC_INFO_ID
--AND    TRN_BASIC_INFO.COMPANY_ID
--AND    TRN_BASIC_INFO.ASST_ID
--AND    TRN_BASIC_INFO.QTR
--AND    TRN_BASIC_INFO.FORM_NO
       

SELECT TRN_CHALLAN.CHALLAN_ID AS CHALLAN_ID,       
       TRN_BASIC_INFO.FORM_NO AS FORM_NO,
       TRN_BASIC_INFO.QTR     AS QTR,
       TRN_CHALLAN.DEPOSIT_DATE AS DEPOSIT_DATE,       
       MST_SECTION.SECTION_ID          AS SECTION_ID,
       MST_SECTION.SECTION_NO          AS SECTION_NO,
       MST_SECTION.SECTION_DESCRIPTION AS SECTION_DESCRIPTION,
       TRN_CHALLAN.BSR_CODE AS BSR_CODE,       
       --CASE
       TRN_CHALLAN.CHALLAN_NO AS CHALLAN_NO,
       TRN_CHALLAN.TDS AS TDS,
       TRN_CHALLAN.OTHERS AS OTHERS,
       TRN_CHALLAN.INTEREST AS INTEREST,
       TRN_CHALLAN.TOT_TAX AS TOT_TAX
FROM   MST_SECTION,
       TRN_CHALLAN,
       TRN_BASIC_INFO
WHERE  MST_SECTION.SECTION_ID      = TRN_CHALLAN.SECTION_ID
AND    TRN_BASIC_INFO.BASIC_INFO_ID = TRN_CHALLAN.BASIC_INFO_ID
--AND    TRN_BASIC_INFO.COMPANY_ID
--AND    TRN_BASIC_INFO.ASST_ID
--AND    TRN_BASIC_INFO.QTR
--AND    TRN_BASIC_INFO.FORM_NO
       

SELECT * FROM MST_SECTION

