
USE TDS-MAN

SELECT * FROM MST_ASSESSMENT

SELECT DISTINCT MST_ASSESSMENT.ASST_ID,
       MST_ASSESSMENT.ASST_YEAR
FROM   MST_ASSESSMENT,
       TRN_BASIC_INFO
WHERE  MST_ASSESSMENT.ASST_ID = TRN_BASIC_INFO.ASST_ID


SELECT * FROM TRN_BASIC_INFO

SELECT START_DATE
FROM   MST_ASSESSMENT
WHERE  ASST_ID = (SELECT MAX(ASST_ID) FROM MST_ASSESSMENT)

SELECT MST_COMPANY.COMPANY_ID                    AS COMPANY_ID,       MST_COMPANY.COMPANY_NAME                  AS COMPANY_NAME,       MST_COMPANY.TAN_NO                        AS TAN_NO,              MST_DEDUCTEE.DEDUCTEE_ID                  AS DEDUCTEE_ID,      MST_DEDUCTEE.DEDUCTEE_NAME                AS DEDUCTEE_NAME,       MST_DEDUCTEE.DEDUCTEE_PAN                 AS DEDUCTEE_PAN,       TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE        AS DEDUCTED_DATE,       MST_SECTION.SECTION_NO                    AS SECTION_NO,       TRN_DEDUCTEE_DETAILS.PAYMENT_AMOUNT       AS PAYMENT_AMOUNT,       TRN_DEDUCTEE_DETAILS.RATE                 AS RATE,       TRN_DEDUCTEE_DETAILS.TOTAL_AMOUNT         AS TOTAL_AMOUNT,       TRN_DEDUCTEE_DETAILS.TAX_DEPOSITED_AMOUNT AS TAX_DEPOSITED_AMOUNT,       TRN_CHALLAN.DEPOSIT_DATE                  AS PAY_DOC_DATE,       TRN_DEDUCTEE_DETAILS.NON_DEDUCTION_FLAG   AS NON_DEDUCTION_FLAG,       MST_ASSESSMENT.FA_YEAR                    AS FA_YEAR FROM   TRN_BASIC_INFO,       TRN_CHALLAN,       TRN_DEDUCTEE_DETAILS,       MST_COMPANY,       MST_DEDUCTEE,       MST_SECTION,       MST_CATEGORY,       MST_ASSESSMENT 
WHERE  TRN_BASIC_INFO.BASIC_INFO_ID       = TRN_CHALLAN.BASIC_INFO_ID 
AND    TRN_CHALLAN.CHALLAN_ID             = TRN_DEDUCTEE_DETAILS.CHALLAN_ID 
AND    TRN_DEDUCTEE_DETAILS.PARTY_ID      = MST_DEDUCTEE.DEDUCTEE_ID 
AND    TRN_CHALLAN.SECTION_ID             = MST_SECTION.SECTION_ID 
AND    MST_COMPANY.COMPANY_ID             = TRN_BASIC_INFO.COMPANY_ID 
AND    MST_CATEGORY.CATEGORY_ID           = MST_COMPANY.D_CATEGORY_ID 
AND    TRN_BASIC_INFO.ASST_ID             = MST_ASSESSMENT.ASST_ID 
AND    TRN_BASIC_INFO.FORM_NO            IN('26Q') 
--AND    TRN_DEDUCTEE_DETAILS.PARTY_ID     IN(154,1868,164,613,1869,153,152) 
AND    TRN_BASIC_INFO.COMPANY_ID           = 30 
AND    TRN_BASIC_INFO.ASST_ID             = 4 
ORDER BY MST_DEDUCTEE.DEDUCTEE_NAME,            TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE,            MST_SECTION.SECTION_NO,            TRN_CHALLAN.CHALLAN_ID

--@@@@@@@@@@@@@@@@@@ ANNUAL
SELECT MST_COMPANY.COMPANY_ID                    AS COMPANY_ID,       
       MST_COMPANY.COMPANY_NAME                  AS COMPANY_NAME,       
       MST_COMPANY.TAN_NO                        AS TAN_NO,    
       MST_DEDUCTEE.DEDUCTEE_ID                  AS DEDUCTEE_ID,         
       MST_DEDUCTEE.DEDUCTEE_NAME                AS DEDUCTEE_NAME,       
       MST_DEDUCTEE.DEDUCTEE_PAN                 AS DEDUCTEE_PAN,       
       MST_SECTION.SECTION_NO                    AS SECTION_NO,       
       SUM(TRN_DEDUCTEE_DETAILS.PAYMENT_AMOUNT) AS PAYMENT_AMOUNT,
       SUM(TRN_DEDUCTEE_DETAILS.TOTAL_AMOUNT)         AS TOTAL_AMOUNT,       
       SUM(TRN_DEDUCTEE_DETAILS.TAX_DEPOSITED_AMOUNT) AS TAX_DEPOSITED_AMOUNT,     
       MST_ASSESSMENT.FA_YEAR                    AS PERIOD 
FROM   TRN_BASIC_INFO,       
       TRN_CHALLAN,       
       TRN_DEDUCTEE_DETAILS,       
       MST_COMPANY,       
       MST_DEDUCTEE,       
       MST_SECTION,        
       MST_ASSESSMENT 
WHERE  TRN_BASIC_INFO.BASIC_INFO_ID       = TRN_CHALLAN.BASIC_INFO_ID 
AND    TRN_CHALLAN.CHALLAN_ID             = TRN_DEDUCTEE_DETAILS.CHALLAN_ID 
AND    TRN_DEDUCTEE_DETAILS.PARTY_ID      = MST_DEDUCTEE.DEDUCTEE_ID 
AND    TRN_CHALLAN.SECTION_ID             = MST_SECTION.SECTION_ID 
AND    MST_COMPANY.COMPANY_ID             = TRN_BASIC_INFO.COMPANY_ID 
AND    TRN_BASIC_INFO.ASST_ID             = MST_ASSESSMENT.ASST_ID 
AND    TRN_BASIC_INFO.FORM_NO            IN('26Q') 
--AND    TRN_DEDUCTEE_DETAILS.PARTY_ID     IN(3845) 
AND    TRN_BASIC_INFO.COMPANY_ID          = 30
AND    TRN_BASIC_INFO.ASST_ID             = 4 
GROUP BY MST_COMPANY.COMPANY_ID,       
       MST_COMPANY.COMPANY_NAME,       
       MST_COMPANY.TAN_NO,    
       MST_DEDUCTEE.DEDUCTEE_ID,         
       MST_DEDUCTEE.DEDUCTEE_NAME,       
       MST_DEDUCTEE.DEDUCTEE_PAN,      
       MST_SECTION.SECTION_NO,     
       MST_ASSESSMENT.FA_YEAR
ORDER BY MST_DEDUCTEE.DEDUCTEE_NAME,           
       MST_SECTION.SECTION_NO

--@@@@@@@@@@@@@@@@@@ QUARTER
--SELECT * FROM TRN_DEDUCTEE_DETAILS WHERE BASIC_INFO_ID IN ( SELECT BASIC_INFO_ID FROM TRN_BASIC_INFO)
--ORDER BY BASIC_INFO_ID, PAYMENT_DATE
--SELECT * FROM TRN_BASIC_INFO
--
SELECT MST_COMPANY.COMPANY_ID                    AS COMPANY_ID,       
       MST_COMPANY.COMPANY_NAME                  AS COMPANY_NAME,       
       MST_COMPANY.TAN_NO                        AS TAN_NO,    
       MST_DEDUCTEE.DEDUCTEE_ID                  AS DEDUCTEE_ID,         
       MST_DEDUCTEE.DEDUCTEE_NAME                AS DEDUCTEE_NAME,       
       MST_DEDUCTEE.DEDUCTEE_PAN                 AS DEDUCTEE_PAN,       
       MST_SECTION.SECTION_NO                    AS SECTION_NO,       
       SUM(TRN_DEDUCTEE_DETAILS.PAYMENT_AMOUNT) AS PAYMENT_AMOUNT,
       SUM(TRN_DEDUCTEE_DETAILS.TOTAL_AMOUNT)         AS TOTAL_AMOUNT,       
       SUM(TRN_DEDUCTEE_DETAILS.TAX_DEPOSITED_AMOUNT) AS TAX_DEPOSITED_AMOUNT,     
       TRN_BASIC_INFO.QTR                    AS PERIOD,
	   0 AS MONTH_ID
FROM   TRN_BASIC_INFO,       
       TRN_CHALLAN,       
       TRN_DEDUCTEE_DETAILS,       
       MST_COMPANY,       
       MST_DEDUCTEE,       
       MST_SECTION,        
       MST_ASSESSMENT 
WHERE  TRN_BASIC_INFO.BASIC_INFO_ID       = TRN_CHALLAN.BASIC_INFO_ID 
AND    TRN_CHALLAN.CHALLAN_ID             = TRN_DEDUCTEE_DETAILS.CHALLAN_ID 
AND    TRN_DEDUCTEE_DETAILS.PARTY_ID      = MST_DEDUCTEE.DEDUCTEE_ID 
AND    TRN_CHALLAN.SECTION_ID             = MST_SECTION.SECTION_ID 
AND    MST_COMPANY.COMPANY_ID             = TRN_BASIC_INFO.COMPANY_ID 
AND    TRN_BASIC_INFO.ASST_ID             = MST_ASSESSMENT.ASST_ID 
AND    TRN_BASIC_INFO.FORM_NO            IN('26Q') 
--AND    TRN_DEDUCTEE_DETAILS.PARTY_ID     IN(3845) 
AND    TRN_BASIC_INFO.COMPANY_ID          = 30 
AND    TRN_BASIC_INFO.ASST_ID             = 4 
GROUP BY MST_COMPANY.COMPANY_ID,       
       MST_COMPANY.COMPANY_NAME,       
       MST_COMPANY.TAN_NO,    
       MST_DEDUCTEE.DEDUCTEE_ID,         
       MST_DEDUCTEE.DEDUCTEE_NAME,       
       MST_DEDUCTEE.DEDUCTEE_PAN,      
       MST_SECTION.SECTION_NO,     
       TRN_BASIC_INFO.QTR
ORDER BY MST_DEDUCTEE.DEDUCTEE_NAME,           
       MST_SECTION.SECTION_NO,
       TRN_BASIC_INFO.QTR

--@@@@@@@@@@@@@@@@@@ MONTHLY
--
SELECT MST_COMPANY.COMPANY_ID                    AS COMPANY_ID,       
       MST_COMPANY.COMPANY_NAME                  AS COMPANY_NAME,       
       MST_COMPANY.TAN_NO                        AS TAN_NO,    
       MST_DEDUCTEE.DEDUCTEE_ID                  AS DEDUCTEE_ID,         
       MST_DEDUCTEE.DEDUCTEE_NAME                AS DEDUCTEE_NAME,       
       MST_DEDUCTEE.DEDUCTEE_PAN                 AS DEDUCTEE_PAN,       
       MST_SECTION.SECTION_NO                    AS SECTION_NO,       
       SUM(TRN_DEDUCTEE_DETAILS.PAYMENT_AMOUNT) AS PAYMENT_AMOUNT,
       SUM(TRN_DEDUCTEE_DETAILS.TOTAL_AMOUNT)         AS TOTAL_AMOUNT,       
       SUM(TRN_DEDUCTEE_DETAILS.TAX_DEPOSITED_AMOUNT) AS TAX_DEPOSITED_AMOUNT,     
       DATENAME(MONTH,TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE) AS PERIOD,
       MONTH(TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE)          AS MONTH_ID
FROM   TRN_BASIC_INFO,       
       TRN_CHALLAN,       
       TRN_DEDUCTEE_DETAILS,       
       MST_COMPANY,       
       MST_DEDUCTEE,       
       MST_SECTION,        
       MST_ASSESSMENT 
WHERE  TRN_BASIC_INFO.BASIC_INFO_ID       = TRN_CHALLAN.BASIC_INFO_ID 
AND    TRN_CHALLAN.CHALLAN_ID             = TRN_DEDUCTEE_DETAILS.CHALLAN_ID 
AND    TRN_DEDUCTEE_DETAILS.PARTY_ID      = MST_DEDUCTEE.DEDUCTEE_ID 
AND    TRN_CHALLAN.SECTION_ID             = MST_SECTION.SECTION_ID 
AND    MST_COMPANY.COMPANY_ID             = TRN_BASIC_INFO.COMPANY_ID 
AND    TRN_BASIC_INFO.ASST_ID             = MST_ASSESSMENT.ASST_ID 
AND    TRN_BASIC_INFO.FORM_NO            IN('26Q') 
--AND    TRN_DEDUCTEE_DETAILS.PARTY_ID     IN(3845) 
AND    TRN_BASIC_INFO.COMPANY_ID          = 30 
AND    TRN_BASIC_INFO.ASST_ID             = 4 
--AND    MONTH(TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE) >= 4
--AND    MONTH(TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE) <= 5
--AND    TRN_CHALLAN.DEPOSIT_DATE = TRN_DEDUCTEE_DETAILS.CHALLAN_ID 
GROUP BY MST_COMPANY.COMPANY_ID,       
       MST_COMPANY.COMPANY_NAME,       
       MST_COMPANY.TAN_NO,    
       MST_DEDUCTEE.DEDUCTEE_ID,         
       MST_DEDUCTEE.DEDUCTEE_NAME,       
       MST_DEDUCTEE.DEDUCTEE_PAN,      
       MST_SECTION.SECTION_NO,     
       DATENAME(month,TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE),
       MONTH(TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE)
ORDER BY MST_DEDUCTEE.DEDUCTEE_NAME,           
       MST_SECTION.SECTION_NO,
       MONTH(TRN_DEDUCTEE_DETAILS.DEDUCTED_DATE)



